#!/usr/bin/env bash
docker-compose  up -d \
&& docker-compose exec --user root apache sh -c "yes 'y' | sendmailconfig" \
# version=$(git describe --tags $(git rev-list --tags --max-count=1))
&& echo "
===================== 🚀 Done 🚀 ===================

      Created by Goran Ninkovic
      v.$version
      Access your new links:

      🌎 Web server: http://localhost/
      ⚙️ PHPMyAdmin: http://localhost:8080
      ✉️ Local emails: http://localhost:8025

===================== 🚀 Done 🚀 ==================="
# docker-compose exec --user root apache sh -c "echo '127.0.0.1 localhost.localdomain localhost $HOSTNAME' >> /etc/hosts";
# docker-compose exec --user root apache sh -c "service sendmail reload";

